version: '3.2'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
  app:  
    restart: always
    build:
       context: .
       dockerfile: "./docker/app.extension"
    volumes:
      - ./www:/var/www
      - ./log/php-fpm:/var/log/php-fpm/www.log
      - ./docker/zz-php-fpm.conf:/usr/local/etc/php-fpm.d/zz-errorlog.conf
      - ./docker/zz-php.conf:/usr/local/etc/php/conf.d/zz-php.ini
    environment:
      PHP_XDEBUG_ENABLED: 1
      
      
      